package org.lab3client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-01-20T20:40:09.343+03:00
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ILab3Service")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, org.datacontract.schemas._2004._07.wcfservicelibrary.ObjectFactory.class})
public interface ILab3Service {

    @WebMethod(operationName = "GetRowsCount", action = "http://tempuri.org/ILab3Service/GetRowsCount")
    @Action(input = "http://tempuri.org/ILab3Service/GetRowsCount", output = "http://tempuri.org/ILab3Service/GetRowsCountResponse")
    @RequestWrapper(localName = "GetRowsCount", targetNamespace = "http://tempuri.org/", className = "org.lab3client.GetRowsCount")
    @ResponseWrapper(localName = "GetRowsCountResponse", targetNamespace = "http://tempuri.org/", className = "org.lab3client.GetRowsCountResponse")
    @WebResult(name = "GetRowsCountResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer getRowsCount()
;

    @WebMethod(operationName = "GetRow", action = "http://tempuri.org/ILab3Service/GetRow")
    @Action(input = "http://tempuri.org/ILab3Service/GetRow", output = "http://tempuri.org/ILab3Service/GetRowResponse")
    @RequestWrapper(localName = "GetRow", targetNamespace = "http://tempuri.org/", className = "org.lab3client.GetRow")
    @ResponseWrapper(localName = "GetRowResponse", targetNamespace = "http://tempuri.org/", className = "org.lab3client.GetRowResponse")
    @WebResult(name = "GetRowResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.wcfservicelibrary.Row getRow(

        @WebParam(name = "i", targetNamespace = "http://tempuri.org/")
        java.lang.Integer i
    );
}
