
package org.lab3client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-01-20T20:40:08.913+03:00
 * Generated source version: 3.5.0
 *
 */
public final class ILab3Service_BasicHttpBindingILab3Service_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "Lab3Service");

    private ILab3Service_BasicHttpBindingILab3Service_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Lab3Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        Lab3Service ss = new Lab3Service(wsdlURL, SERVICE_NAME);
        ILab3Service port = ss.getBasicHttpBindingILab3Service();

        {
        System.out.println("Invoking getRowsCount...");
        java.lang.Integer _getRowsCount__return = port.getRowsCount();
        System.out.println("getRowsCount.result=" + _getRowsCount__return);


        }
        {
        System.out.println("Invoking getRow...");
        java.lang.Integer _getRow_i = Integer.valueOf(-635632396);
        org.datacontract.schemas._2004._07.wcfservicelibrary.Row _getRow__return = port.getRow(_getRow_i);
        System.out.println("getRow.result=" + _getRow__return);


        }

        System.exit(0);
    }

}
