package org.lab3client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-01-20T20:40:09.366+03:00
 * Generated source version: 3.5.0
 *
 */
@WebServiceClient(name = "Lab3Service",
                  wsdlLocation = "http://25.46.195.40:8080/service?singleWsdl",
                  targetNamespace = "http://tempuri.org/")
public class Lab3Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "Lab3Service");
    public final static QName BasicHttpBindingILab3Service = new QName("http://tempuri.org/", "BasicHttpBinding_ILab3Service");
    static {
        URL url = null;
        try {
            url = new URL("http://25.46.195.40:8080/service?singleWsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Lab3Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://25.46.195.40:8080/service?singleWsdl");
        }
        WSDL_LOCATION = url;
    }

    public Lab3Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Lab3Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Lab3Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Lab3Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Lab3Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Lab3Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ILab3Service
     */
    @WebEndpoint(name = "BasicHttpBinding_ILab3Service")
    public ILab3Service getBasicHttpBindingILab3Service() {
        return super.getPort(BasicHttpBindingILab3Service, ILab3Service.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ILab3Service
     */
    @WebEndpoint(name = "BasicHttpBinding_ILab3Service")
    public ILab3Service getBasicHttpBindingILab3Service(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingILab3Service, ILab3Service.class, features);
    }

}
